language: clojure
lein: lein
before_script:
  - ./bin/ci/install_mongodb.sh
  - mongod --version
  - ./bin/ci/before_script.sh
script: lein do clean, javac, test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
branches:
  only:
    - master
    - 3.0.x-stable
